apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zestful-crocodile-python 
  janus-idp.io/tekton: zestful-crocodile-python
  backstage.io/kubernetes-id: zestful-crocodile-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: zestful-crocodile-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  