apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: zestful-crocodile-python
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:2128d9fd67a877fb648f40046e60d4cb813e2f03@sha256:a79e3496549bbf91b1a19f322e7a9e991ddc6c78da12c0149d826f1a8ee926ef
        name: container-image  
